plugins {
    id 'java'
    id 'java-library'
    id 'maven-publish'
}

group = 'com.graphql-java-calculator'
version = '1.0.5-SNAPSHOT'

repositories {
    mavenCentral()
    mavenLocal()
}

apply plugin: 'groovy'

dependencies {
    implementation group: 'com.graphql-java', name: 'graphql-java', version: '21.5'
    implementation group: 'com.googlecode.aviator', name: 'aviator', version: '5.3.3'
    implementation group: 'org.slf4j', name: 'slf4j-api', version: '2.0.3'
    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
    testImplementation 'org.spockframework:spock-core:2.3-groovy-4.0'
    testImplementation 'org.apache.groovy:groovy-all:4.0.15'
    testImplementation 'ch.qos.logback:logback-classic:1.4.14'
    testRuntimeOnly 'org.junit.vintage:junit-vintage-engine:5.10.0'
}

test {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withJavadocJar()
    withSourcesJar()
}

javadoc {
    options.encoding = 'UTF-8'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'graphql-java-calculator'
            from components.java

            pom {
                name = 'graphql-java-calculator'
                description = 'graphql-java-calculator'
                url = 'https://github.com/dugenkui03/graphql-java-calculator'

                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                developers {
                    developer {
                        id = 'dugenkui'
                        name = 'dugenkui'
                        email = 'dugk@foxmail.com'
                    }
                }
                scm {
                    connection = 'scm:git:https://github.com/dugenkui03/graphql-java-calculator.git'
                    developerConnection = 'scm:git:https://github.com/dugenkui03/graphql-java-calculator.git'
                    url = 'https://github.com/dugenkui03/graphql-java-calculator'
                }
            }
        }
    }

    repositories {
        maven {
            name = "OSSRH"
            def snapshotUrl = "https://oss.sonatype.org/content/repositories/snapshots"
            def releaseUrl = "https://oss.sonatype.org/service/local/staging/deploy/maven2"
            url = version.endsWith('SNAPSHOT') ? snapshotUrl : releaseUrl
            credentials {
                username =  'username'
                password = 'password'
            }
        }
    }
}